version: '3.8'

services:
  frontend:
    build: /InsightsFrontend
    image: ghcr.io/frankframework/insights:${VERSION:-frontend}
    restart: always
    networks:
      - FFInsightsNetwork
    depends_on:
      - backend
    ports:
      - "8080:80"
    container_name: frontend

  backend:
    build: /InsightsBackend
    image: ghcr.io/frankframework/insights:${VERSION:-backend}
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: insights
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      GITHUB_API_SECRET: dummytoken
    networks:
      - FFInsightsNetwork
    depends_on:
      - db
    ports:
      - "8080:8080"
    container_name: backend

  db:
    image: postgres:17-alphine3.22
    restart: always
    environment:
      POSTGRES_DB: insights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - FFInsightsNetwork
    ports:
      - "5432:5432"

networks:
  FFInsightsNetwork:
    driver: bridge

volumes:
  pg-data:
