packages:
  - src/main/frontend
  - src/main/frontend/cypress

overrides:
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  qs@<6.14.1: '>=6.14.1'
  systeminformation@<5.27.14: '>=5.27.14'
  tar@<=7.5.2: '>=7.5.3'
  tar@<=7.5.3: '>=7.5.4'
