spring.datasource.url=jdbc:h2:mem:e2edb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.username=sa
spring.datasource.password=password

data.fetch-enabled=false

spring.flyway.locations=classpath:db/migration,classpath:db/e2e

cors.allowed.origins[0]=http://localhost:4200
cors.allowed.origins[1]=http://localhost:8080

spring.security.oauth2.client.registration.github.client-id=test-client-id
spring.security.oauth2.client.registration.github.client-secret=test-client-secret

server.servlet.session.cookie.http-only=true
frankframework.security.csrf.secure=false
