spring.config.import=classpath:insights-common.properties

spring.application.name=insights-webapp
server.port=${SERVER_PORT:8080}

spring.security.oauth2.client.registration.github.scope=read:user,read:org
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.web.resources.static-locations=classpath:/frontend/

server.tomcat.relaxed-query-chars=[,]

server.servlet.session.cookie.same-site=lax

insights.rate-limit.protected-paths[0]=/api/auth
insights.rate-limit.protected-paths[1]=/api/business-value
insights.rate-limit.protected-paths[2]=/api/vulnerabilities
insights.rate-limit.exempt-paths[0]=/api/business-value/release
insights.rate-limit.exempt-paths[1]=/api/vulnerabilities/release
