spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/insightsdb
spring.datasource.username=user
spring.datasource.password=password

spring.security.oauth2.client.registration.github.client-id=test-client-id
spring.security.oauth2.client.registration.github.client-secret=test-client-secret

cors.allowed.origins[0]=http://localhost:4200
cors.allowed.origins[1]=http://localhost:8080

frankframework.security.csrf.secure=false
