spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/insightsdb
spring.datasource.username=user
spring.datasource.password=password

data.fetch-enabled=true

github.graphql.secret=github-pat
github.graphql.project-id=github-graphql-project-id

insights.webhook.secret=webhook-hmac-secret

trivy.path=C:/Users/user/scoop/apps/trivy/x.xx.x/trivy.exe
