spring.config.import=classpath:insights-common.properties

spring.application.name=insights-data-import
server.port=${SERVER_PORT:8081}

data.fetch-enabled=false

release.archive.directory=/release-archive
trivy.scan.workspace=/tmp/trivy-scan
trivy.db.cache=/tmp/trivy-cache
maven.local-repo=/release-archive/.m2
