name: CI - FF Insights

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

env:
  JDK_VERSION: 21
  NODE_VERSION: 23

jobs:
  backend-lint:
    name: Backend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
      - name: Lint backend
        run: mvn clean checkstyle:check | tee backend-lint.log
        working-directory: InsightsBackend
      - name: Upload Backend Lint Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-lint-log
          path: InsightsBackend/backend-lint.log

  frontend-lint:
    name: Frontend Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: npm ci
        working-directory: InsightsFrontend
      - name: Lint frontend
        run: npm run lint | tee frontend-lint.log
        working-directory: InsightsFrontend
      - name: Upload Frontend Lint Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-lint-log
          path: InsightsFrontend/frontend-lint.log

  backend-test:
    name: Backend Unit Test
    runs-on: ubuntu-latest
    needs: [backend-lint]
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports: [5432:5432]
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JDK_VERSION }}
          distribution: 'temurin'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: maven-${{ runner.os }}-
      - name: Backend Unit Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: testuser
          POSTGRES_PASSWORD: testpass
        run: mvn test --file pom.xml | tee test.log
        working-directory: InsightsBackend
      - name: Upload Backend Test Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-logs
          path: |
            InsightsBackend/target/surefire-reports/
            InsightsBackend/test.log

  frontend-test:
    name: Frontend Unit Test
    runs-on: ubuntu-latest
    needs: [frontend-lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: InsightsFrontend/node_modules
          key: npm-${{ runner.os }}-${{ hashFiles('InsightsFrontend/package-lock.json') }}
          restore-keys: npm-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
        working-directory: InsightsFrontend
      - name: Frontend Unit Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless | tee test.log
        working-directory: InsightsFrontend
      - name: Upload Frontend Test Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: frontend-test-logs
          path: InsightsFrontend/test.log

  e2e-test:
    name: End-to-End Testing
    runs-on: ubuntu-latest
    needs: [backend-test, frontend-test]
    steps:
      - uses: actions/checkout@v4
      - name: Install jq
        run: sudo apt-get -y install jq
      - name: CI Install
        run: npm ci
        working-directory: InsightsFrontend
      - name: Start Docker Compose
        run: |
          docker compose up -d --build 
          docker compose logs backend
          docker logs backend
      - name: Wait for Backend Health
        run: |
          echo "Pinging backend health endpoint..."
          RETRY_COUNT=10
          MAX_RETRIES=30
          RETRY_INTERVAL=5
          until [ "$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8080/api/releases)" -eq 200 ]; do
            if [ ${RETRY_COUNT} -ge ${MAX_RETRIES} ]; then
              echo "Health check failed after ${MAX_RETRIES} retries. Backend is not healthy."
              docker compose logs
              docker compose logs backend
              exit 1
            fi
            RETRY_COUNT=$((RETRY_COUNT + 1))
            echo "Backend not ready yet. Retrying in ${RETRY_INTERVAL}s... (Attempt ${RETRY_COUNT}/${MAX_RETRIES})"
            sleep ${RETRY_INTERVAL}
          done
          echo "Backend is healthy!"
      - name: Verify API Data
        run: |
          echo "Fetching data from /api/releases to verify data loading..."
          RESPONSE=$(curl --silent --fail http://localhost:8080/api/releases)
          COUNT=$(echo "$RESPONSE" | jq 'length')
          if [ "$COUNT" -gt 0 ]; then
            echo "Success! Found $COUNT releases in the database."
            echo "Response JSON:"
            echo "$RESPONSE"
          else
            echo "Error: Backend is up, but no data was found (/api/releases returned an empty array)."
            echo "Dumping dataloader logs:"
            docker compose logs dataloader
            exit 1
          fi
      - name: additional sleep to wait for data loader
        run: sleep 30
      - name: Run Cypress tests
        working-directory: ./InsightsFrontend
        run: npm run cypress:run | tee e2e.log
      - name: Stop Docker Compose on failure
        if: ${{ failure() }}
        run: docker compose down
      - name: Upload E2E Test Logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-logs
          path: InsightsFrontend/e2e.log

  docker-dispatch:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [e2e-test]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Docker Publish workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: docker-publish
