name: Backend Integration Tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: insights
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./InsightsFrontend

      - name: Build Backend
        run: mvn clean package -DskipTests
        working-directory: ./InsightsBackend

      - name: Install Playwright
        run: |
          npm install --save-dev @playwright/test
          npx playwright install --with-deps
        working-directory: ./InsightsFrontend

      - name: Full application check
        env:
          GITHUB_API_SECRET: ${{ secrets.GH_TOKEN }}
        run: |
          chmod +x .github/workflows/scripts/full_application_check.sh
          .github/workflows/scripts/full_application_check.sh
