on:
  workflow_dispatch:
  pull_request:

jobs:
  stress-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: insights
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker compose up
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: sleep 30

      - name: Stress test Backend (Apache Bench)
        run: ab -r -n 5000 -c 250 http://localhost:8080/api/releases > backend.log || true

      - name: Stress test Frontend (Apache Bench)
        run: ab -r -n 5000 -c 250 http://localhost/ > frontend.log || true

      - name: Upload Apache Bench logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apache-bench-logs
          path: |
            backend.log
            frontend.log
            
