name: Stress Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '**'  # zodat dit ook werkt op subbranches

jobs:
  stress-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: insights
        ports:
          - 5432:5432

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Backend Container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/${{ github.repository }}-backend:master
          options: >-
            --name backend
            --rm
            -e SPRING_PROFILES_ACTIVE=local
            -e GITHUB_SECRET=${{ secrets.GH_TOKEN }}
            -p 8080:8080
            --health-cmd "curl -f http://localhost:8080/actuator/health || exit 1"
            --health-interval 5s
            --health-retries 5
          detach: true

      - name: Run Frontend Container
        uses: addnab/docker-run-action@v3
        with:
          image: ghcr.io/${{ github.repository }}-frontend:master
          options: >-
            --name frontend
            --rm
            -p 80:80
          detach: true

      - name: Wait for frontend to start
        run: sleep 10

      - name: Health Check - Backend
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://localhost:8080/actuator/health
          follow-redirect: false
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - name: Health Check - Frontend
        uses: jtalk/url-health-check-action@v4
        with:
          url: http://localhost/
          follow-redirect: true
          max-attempts: 5
          retry-delay: 5s
          retry-all: true

      - name: Install Apache Bench
        run: sudo apt-get update && sudo apt-get install -y apache2-utils

      - name: Stress test Backend (Apache Bench)
        run: ab -n 1000 -c 50 http://localhost:8080/api/releases > backend.log || true

      - name: Stress test Frontend (Apache Bench)
        run: ab -n 1000 -c 50 http://localhost/ > frontend.log || true

      - name: Upload Apache Bench logs
        uses: actions/upload-artifact@v4
        with:
          name: apache-bench-logs
          path: |
            backend.log
            frontend.log
