name: Stress Tests

on:
  workflow_dispatch:

jobs:
  stress-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: insights
        ports:
          - 5432:5432

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Backend Container
        run: |
          docker run -d \
            --name backend \
            -e SPRING_PROFILES_ACTIVE=local \
            -e GITHUB_SECRET=${{ secrets.GH_TOKEN }} \
            --health-cmd="curl -f http://localhost:8080/actuator/health || exit 1" \
            --health-interval=5s \
            --health-retries=5 \
            -p 8080:8080 \
            ghcr.io/${{ github.repository }}-backend:master

      - name: Run Frontend Container
        run: |
          docker run -d \
            --name frontend \
            --health-cmd="curl -f http://localhost:80/ || exit 1" \
            --health-interval=5s \
            --health-retries=5 \
            -p 80:80 \
            ghcr.io/${{ github.repository }}-frontend:master

      - name: Install Apache Bench
        run: sudo apt-get update && sudo apt-get install -y apache2-utils

      - name: Stress test Backend (Apache Bench)
        run: ab -r -n 1000 -c 50 http://localhost:8080/api/releases > backend.log || true

      - name: Stress test Frontend (Apache Bench)
        run: ab -r -n 1000 -c 50 http://localhost/ > frontend.log || true

      - name: Upload Apache Bench logs
        uses: actions/upload-artifact@v4
        with:
          name: apache-bench-logs
          path: |
            backend.log
            frontend.log
