on:
  workflow_dispatch:
  pull_request:

jobs:
  stress-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: insights
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Backend image
        working-directory: InsightsBackend
        run: docker build -t local-backend:latest .

      - name: Run Backend Container
        run: |
          docker run -d \
            --name backend \
            -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=local \
            -e SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/insights \
            local-backend:latest

      - name: Build Frontend image
        working-directory: InsightsBackend
        run: docker build -t local-frontend:latest .

      - name: Run Frontend Container
        run: |
          docker run -d \
            --name frontend \
            -p 80:80 \
            local-frontend:latest

      - name: Install test tools
        run: sudo apt-get update && sudo apt-get install -y apache2-utils curl

      - name: Wait for Backend to be ready
        run: |
          echo "Waiting for backend..."
          until curl --fail --silent --output /dev/null http://localhost:8080/actuator/health; do
            echo -n '.'
            sleep 5
          done
          echo "Backend is up!"

      - name: Stress test Backend (Apache Bench)
        run: ab -r -n 100 -c 5 http://localhost:8080/api/releases > backend.log || true

      - name: Stress test Frontend (Apache Bench)
        run: ab -r -n 100 -c 5 http://localhost/ > frontend.log || true

      - name: Upload Apache Bench logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: apache-bench-logs
          path: |
            backend.log
            frontend.log
            
